models/service_panel.py
from utils.db import db

class service_panel(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False, unique=True)
    t_max = db.Column(db.Integer, nullable=False)
    t_min = db.Column(db.Integer, nullable=False)
    h_max = db.Column(db.Integer, nullable=False)
    h_min = db.Column(db.Integer, nullable=False)
    co2_min = db.Column(db.Integer, nullable=False)
    co2_max = db.Column(db.Integer, nullable=False)

    def __init__(self, tmax, tmin, hmax, hmin, co2max, co2min) -> None:
        self.t_max = tmax
        self.t_min = tmin
        self.h_max = hmax
        self.h_min = hmin
        self.co2_max = co2max
        self.co2_min = co2min

    def save(self):
        if not self.id:
            db.session.add(self)
        db.session.commit()

    @staticmethod
    def get_by_id(uid):
        return service_panel.query.filter_by(id=uid)

    def __repr__(self) -> str:
        return "<service-panel id={}>".format(self.id)

routes/dashboard.py
from flask import Blueprint, render_template
from flask_login import login_required
from routes.decorator import superadmin_required, role_required

dashboard = Blueprint("dashboard",__name__)

# Ajustes del usuario
@dashboard.route("/user-settings")
@login_required
def user_settings():
    return render_template("user-settings.html")

# Visión general
@dashboard.route("/overview")
@login_required
def overview():
    return render_template("overview.html")

# Panel de servicio
@dashboard.route("/service-panel")
@login_required
def service_panel():
    return render_template("service-panel.html")

# Gestión de usuarios
@dashboard.route("/users")
@login_required
@role_required(role=["Superadmin"])
def users_manager():
    return render_template("users-dashboard.html", css="css/user-manager.css")

# Ajustes de la cuenta del usuario
@dashboard.route("/account")
@login_required
def my_account():
    return render_template("account.html",css="css/account.css")

routes/root.py
from flask import Blueprint, render_template, redirect
from flask_login import login_required, current_user
from models.Forms.LoginForm import LoginForm

root = Blueprint("root",__name__)

@root.route("/")
def index():
    if current_user.is_authenticated:
        return redirect("dashboard")

    return render_template("index.html", css="index.css", form=LoginForm())

@root.route("/dashboard")
@login_required
def profile_user():
    return render_template("dashboard.html", css="css/profile.css")

routes/service_panel.py
from flask import Blueprint, request
from models.service_panel import service_panel as sp

service_panel = Blueprint("service_panel",__name__)

@service_panel.route("/add-parameters",methods=["POST"])
def _add_data():
    data = request.get_json()
    print(data)
    parameters = sp(data["t-max"],data["t-min"],data["h-max"],data["h-min"],data["co2-max"],data["co2-min"])
    parameters.save()
    return "Éxito", 200, {"Content-Type": "text/plain"}

templates/account.html
{% extends 'template_base.html' %}

{% block title %}Mi cuenta{% endblock %}

{% block content %}
    <nav>
        <h4><a href="/dashboard">Inicio</a></h4>
        <ul>
            <li><a href="/logout">Cerrar sesión</a></li>
        </ul>
    </nav>

    <div class="container">
        <div class="profile-box">
            <h3>{{ current_user.Name }}</h3>
            <p>Email: {{ current_user.Email }}</p>
            <p>Rut: {{ current_user.Rut }}</p>
            <p>Rol: {{ current_user.Type }}</p>
            <div class="settings">
                <button class="one"><span>Nombre</span></button>
                <button class="two"><span>Correo Electrónico</span></button>
                <button class="three"><span>Contraseña</span></button>
            </div>
        </div>
    </div>

    <div id="name" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>Actualizar nombre.</p>
            <hr />
            <div class="input-group">
                <input type="text" id="update-name" class="input" required>
                <label for="update-name" class="input-label">Nuevo nombre</label>
            </div>
            <button class="btn one" id="name-btn"><span>Actualizar</span></button>
        </div>
    </div>

    <div id="email" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>Actualizar correo electrónico.</p>
            <hr />
            <div class="input-group">
                <input type="email" id="update-email" class="input" required>
                <label for="update-email" class="input-label">Nuevo correo</label>
            </div>
            <button class="btn two" id="email-btn"><span>Actualizar</span></button>
        </div>
    </div>

    <div id="password" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <p>Actualizar contraseña.</p>
            <hr />
            <div class="input-group">
                <input type="password" id="current-password" class="input" required>
                <label for="current-password" class="input-label">Contraseña actual</label>
            </div>
            <div class="input-group">
                <input type="password" id="new-password" class="input" required>
                <label for="new-password" class="input-label">Nueva contraseña</label>
            </div>
            <button class="btn three" id="update-password"><span>Actualizar</span></button>
        </div>
    </div>

    <script defer src="../static/js/account.js"></script>

{% endblock %}

templates/dashboard.html
{% extends 'template_base.html' %}

{% block title %}Demo{% endblock %}

{% block content %} 

    <nav>
        <h4>¡Bienvenido, {{ current_user.Name }}!</h4>
        <ul>
            <li><a href="/account">Mi cuenta</a></li>
            <li><a href="/logout">Cerrar sesión</a></li>
        </ul>
    </nav>

    <div class="container">
        <div class="cards-container">

            <input type="radio" name="dot" id="one">
            <input type="radio" name="dot" id="two">
    
            <div class="main-card">
                <div class="cards">
                    <div class="card">
                        <a href="/user-settings">
                            <div class="content">
                                <div class="img">
                                    <img src="../static/img/profile.svg" alt="">
                                </div>
                                <div class="details">
                                    <h1 class="title">Ajustes de usuario</h1>
                                </div>
                            </div>
                        </a>
                    </div>
    
                    <div class="card">
                        <a href="/overview">
                            <div class="content">
                                <div class="img">
                                    <img src="../static/img/overview.svg" alt="">
                                </div>
                                <div class="details">
                                    <h1 class="title">Visión general</h1>
                                </div>
                            </div>
                        </a>
                    </div>
    
                    <div class="card">
                        <a href="/service-panel">
                            <div class="content">
                                <div class="img">
                                    <img src="../static/img/service-panel.svg" alt="">
                                </div>
                                <div class="details">
                                    <h1 class="title">Panel de servicio</h1>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
    
                <div class="cards">
                    <!--
                    <div class="card">
                        <a href="/temperature">
                            <div class="content">
                                <div class="img">
                                    <img src="../static/img/temperature.svg" alt="">
                                </div>
                                <div class="details">
                                    <div class="title">Temperatura promedio</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    -->
    
                    <div class="card">
                        <a href="/register">
                            <div class="content">
                                <div class="img">
                                    <img src="../static/img/add_user.svg" alt="">
                                </div>
                                <div class="details">
                                    <div class="title">Registro de usuarios</div>
                                </div>
                            </div>
                        </a>
                    </div>
    
                    <div class="card">
                        <a href="/users">
                            <div class="content">
                                <div class="img">
                                    <img src="../static/img/users.svg" alt="">
                                </div>
                                <div class="details">
                                    <div class="title">Gestión de usuarios</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    
                </div>
            </div>
            <div class="button">
                <label for="one" class="one active"></label>
                <label for="two" class="two"></label>
            </div>
        </div>
    </div>


{% endblock %}

templates/error.html
{% extends 'template_base.html' %}

{% block title %}{{ error["title"] }}{% endblock %}

{% block content %}
<div class="container">
    <div class="bg">
        <img src='{{ error["img"] }}' alt="Error 401">
    </div>
    {{ error["message"] }}
    <a href="/">Volver a inicio</a>
</div>
{% endblock %}

templates/index.html
{% extends 'template_base.html' %}

{% block title %}Demo{% endblock %}

{% block content %}
    <nav class="navBar">
        <div class="navBarItem">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                {{ messages[0] }}
            {% endif %}
            {% endwith %}
        </div>
        <form action="/login" method="post">
            {{ form.hidden_tag() }}
            <div class="navBarItem">
                {{ form.username.label }}
                {{ form.username(placeholder="Ingrese su rut") }}
            </div>
            <div class="navBarItem">
                {{ form.password.label }}
                {{ form.password(placeholder="Ingrese su contraseña") }}
            </div>
            <div class="navBarItem">
                <a href="#">¿Ha olvidado la contraseña?</a>
            </div>
            {{ form.submit(class="btn") }}
        </form>
    </nav>
{% endblock %}

templates/overview.html
{% extends 'template_base.html' %}

{% block title %}Visión General{% endblock %}

{% block content %}

<nav>
    <h4><a href="/dashboard">Inicio</a></h4>
    <ul>
        <li><a href="/logout">Cerrar sesión</a></li>
    </ul>
</nav>

<div class="container">
    <table class="content-table">
        <thead>
            <tr>
                <th>Humedad</th>
                <th>Temperatura</th>
                <th>CO2</th>
            </tr>
        </thead>
        <tbody id="overview-data"></tbody>
    </table>
</div>

<script defer src="../static/js/overview.js"></script>
{% endblock %}

templates/register.html
{% extends 'template_base.html' %}

{% block title %}Registrar{% endblock %}

{% block content %}

    <nav>
        <h4><a href="/dashboard">Inicio</a></h4>
        <ul>
            <li><a href="/logout">Cerrar sesión</a></li>
        </ul>
    </nav>

    <section class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification">
                {{ messages[0] }}. Ve a <a href="{{ url_for('root.index') }}">iniciar sesión</a>
            </div>
        {% endif %}
        {% endwith %}
        <form action="/register" method="post">
            {{ form.hidden_tag() }}
            <div class="input-group">
                {{ form.name(class="input") }}
                <label for="name" class="input-label">Ingrese su nombre</label>
            </div>
            <div class="input-group">
                {{ form.password(class="input") }}
                <label for="password" class="input-label">Ingrese una contraseña</label>
            </div>
            <div class="input-group">
                {{ form.rut(class="input") }}
                <label for="Rut" class="input-label">Ingrese su rut</label>
            </div>
            <div class="input-group">
                {{ form.email(class="input") }}
                <label for="email" class="input-label">Ingrese su correo</label>
            </div>
            <div class="input-group">
                {{ form.type_user(class="input") }}
                <label for="user_rol" class="input-label">Seleccione un rol</label>
            </div>
            <button type="submit" class="btn-p one">
                <span>Registrar</span>
            </button>
        </form>
    </section>
{% endblock %}

templates/service-panel.html
{% extends 'template_base.html' %}

{% block title %}Panel de servicio{% endblock %}

{% block content %}

<div class="container">
    <div>
        <div class="input-group-2">
            <label>Temperatura</label>
            <div class="sub-input-group">
                <div class="input-group">
                    <input type="number" id="t-min" class="input" required>
                    <label for="t-min" class="input-label">Mínimo</label>
                </div>
                <div class="input-group">
                    <input type="number" id="t-max" class="input" required>
                    <label for="t-max" class="input-label">Máximo</label>
                </div>
            </div>
        </div>

        <div class="input-group-2">
            <label>Humedad</label>
            <div class="sub-input-group">
                <div class="input-group">
                    <input type="number" id="h-min" class="input" required>
                    <label for="h-min" class="input-label">Mínimo</label>
                </div>
                <div class="input-group">
                    <input type="number" id="h-max" class="input" required>
                    <label for="h-max" class="input-label">Máximo</label>
                </div>
            </div>
        </div>

        <div class="input-group-2">
            <label>CO2</label>
            <div class="sub-input-group">
                <div class="input-group">
                    <input type="number" id="c-min" class="input" required>
                    <label for="c-min" class="input-label">Mínimo</label>
                </div>
                <div class="input-group">
                    <input type="number" id="c-max" class="input" required>
                    <label for="c-max" class="input-label">Máximo</label>
                </div>
            </div>
        </div>
        
        <button class="btn-p one" id="send">
            <span>Registrar</span>
        </button>
    </div>
</div>

<script defer src="../static/js/service-panel.js"></script>

{% endblock %}

templates/template_base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="../static/css/base.css">
    {% if css %}
        <link rel="stylesheet" href="{{url_for('static',filename=css)}}">
    {% endif %}
</head>
<body>
    {% block content %}{% endblock %}
    <script defer src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</body>
</html>

templates/users-dashboard.html
{% extends 'template_base.html' %}

{% block title %}Gestión de usuarios{% endblock %}

{% block content %}

<nav>
    <h4><a href="/dashboard">Inicio</a></h4>
    <ul>
        <li><a href="/logout">Cerrar sesión</a></li>
    </ul>
</nav>

<div class="container">

    <div class="search">
        <div class="input-group">
            <input type="text" id="search-username" class="input" required>
            <label for="search-username" class="input-label">Buscar por RUT</label>
        </div>
    </div>

    <table class="content-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Usuario</th>
                <th>Email</th>
                <th>Rol</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody id="users"></tbody>
    </table>
</div>

<div class="modal" id="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p>Datos personales</p>
        <hr />

        <div class="input-group">
            <input type="number" id="uid" class="input" disabled>
            <label for="uid" class="input-label">Identificador</label>
        </div>

        <div class="input-group">
            <input type="text" id="name" class="input" disabled>
            <label for="name" class="input-label">Nombre y/o Apellido</label>
        </div>

        <div class="input-group">
            <input type="text" id="rut" class="input" disabled>
            <label for="rut" class="input-label">RUT</label>
        </div>

        <div class="input-group">
            <input type="email" id="email" class="input" disabled>
            <label for="email" class="input-label">Correo electrónico</label>
        </div>

        <div class="input-group">
            <select id="user_rol" class="input" required>
                <option value="User">User</option>
                <option value="admin">admin</option>
                <option value="Superadmin">Superadmin</option>
            </select>
            <label for="user_rol" class="input-label">Seleccione un rol</label>
        </div>

        <div class="actions">
            <button class="btn three" id="update-rol"><span>Actualizar Rol</span></button>
            <button class="btn four" id="delete-user"><span>Eliminar Usuario</span></button>
        </div>
    
    </div>
</div>

<script defer src="../static/js/user-manager.js"></script>

{% endblock %}